apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: salutation-app
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: 'https://github.com/username/examen-devops.git'
    targetRevision: HEAD
    path: 'k8s'
  syncPolicy:
    automated: {}
